title: SeaHUG
description: Agendas and minutes of SeaHUG monthly meetings
author: Richard Cook
author_email: rcook@rcook.org
layouts_dir: _layouts
excerpt_separator: <!--more-->
plugins:
- jekyll-gist
